spring:
  application:
    name: back

app:
  reset-token:
    secret: ${RESET_TOKEN_SECRET:change-me-in-production}


logging:
  file:
    name: logs/back.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/back-%d{yyyy-MM-dd}.%i.log